/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CmDrawer {
        "drawertitle": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface CmStockPrice {
    }
    interface CmTooltip {
        "message": string;
    }
}
declare global {
    interface HTMLCmDrawerElement extends Components.CmDrawer, HTMLStencilElement {
    }
    var HTMLCmDrawerElement: {
        prototype: HTMLCmDrawerElement;
        new (): HTMLCmDrawerElement;
    };
    interface HTMLCmStockPriceElement extends Components.CmStockPrice, HTMLStencilElement {
    }
    var HTMLCmStockPriceElement: {
        prototype: HTMLCmStockPriceElement;
        new (): HTMLCmStockPriceElement;
    };
    interface HTMLCmTooltipElement extends Components.CmTooltip, HTMLStencilElement {
    }
    var HTMLCmTooltipElement: {
        prototype: HTMLCmTooltipElement;
        new (): HTMLCmTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "cm-drawer": HTMLCmDrawerElement;
        "cm-stock-price": HTMLCmStockPriceElement;
        "cm-tooltip": HTMLCmTooltipElement;
    }
}
declare namespace LocalJSX {
    interface CmDrawer {
        "drawertitle"?: string;
        "opened"?: boolean;
    }
    interface CmStockPrice {
    }
    interface CmTooltip {
        "message"?: string;
    }
    interface IntrinsicElements {
        "cm-drawer": CmDrawer;
        "cm-stock-price": CmStockPrice;
        "cm-tooltip": CmTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-drawer": LocalJSX.CmDrawer & JSXBase.HTMLAttributes<HTMLCmDrawerElement>;
            "cm-stock-price": LocalJSX.CmStockPrice & JSXBase.HTMLAttributes<HTMLCmStockPriceElement>;
            "cm-tooltip": LocalJSX.CmTooltip & JSXBase.HTMLAttributes<HTMLCmTooltipElement>;
        }
    }
}
